### ISSUE TITLE
Error 1020 Cloudflare security

### ISSUE THREAD

**Issue by Xelo** [koonweee/koonweee.github.io#1]
Hey,
cloudflare is blocking access to your site, can you try to fix it?
https://www.minitool.com/news/cloudflare-error-1020-access-denied-fix.html

Best,
zerant

**Comment by koonweee** [comment]
Hi zerant,

Thank you for raising the issue. I believe that it is working now and https://config.makercube.me is accessible. Could you confirm on your end?

Regards
Jeremy

**Comment by Xelo** [comment]
Sorry for the late delay, it looks good now. Thanks!
